version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    image: "scc-server"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    image: "scc-client"
    ports:
      - "3000:3000"
    links:
      - "server:sr"