#Stage 0 - Build Frontend Assets
FROM node:12.21.0-alpine

WORKDIR /app-client
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 3000
RUN apk update && apk add --no-cache supervisor openssh nginx
COPY supervisord.conf /etc/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]