#Stage 0 - Build Frontend Assets
FROM node:12.21.0-alpine

WORKDIR /app-client
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 3000
RUN apt-get update && apt-get install -y supervisor
ADD supervisord.config /etc/supervisor/conf.d/supervisord.conf


