#Stage 0 - Build Frontend Assets
FROM node:12.21.0-alpine

WORKDIR /app-client
COPY package*.json ./
RUN npm install --silent
RUN curl -sS0 https://dl.google.com/cloudagents/install-monitoring-agent.sh
RUN sudo bash install-monitoring-agent.sh
COPY . .
EXPOSE 3000
CMD ["npm", "start"]

