#Stage 0 - Build Frontend Assets
FROM node:12.21.0-alpine

WORKDIR /app-server
COPY package*.json ./
RUN npm install --silent
COPY . .
EXPOSE 8080
CMD ["npm", "run", "devstart"]
RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json
RUN npm install --silent

CMD ["npm", "run", "devstart"]


