name: Firestore Backups
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Backup'
        default: 'Backup'
        required: false
  schedule:
    - cron: '0 23 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - run: gcloud config set project cloud-development-e159d
      - run: gcloud firestore export gs://firestore-backup-us
      - run: gcloud firestore export gs://firestore-backup-eur
      - run: gcloud firestore export gs://firestore-backup-asia-multi
